melhorias diversas

diff --git a/vpndnsutils/DEBIAN/postinst b/vpndnsutils/DEBIAN/postinst
--- a/vpndnsutils/DEBIAN/postinst
+++ b/vpndnsutils/DEBIAN/postinst
@@ -1,12 +1,29 @@
+#!/bin/bash
+
+NONE='\033[00m'
+RED='\033[01;31m'
+GREEN='\033[01;32m'
+YELLOW='\033[01;33m'
+PURPLE='\033[01;35m'
+CYAN='\033[01;36m'
+WHITE='\033[01;37m'
+BOLD='\033[1m'
+UNDERLINE='\033[4m'
+
 systemctl enable vpndnsutils
 
-echo -n "Please enter your QA DNS Server address? [e.g. 8.8.8.8] "
+echo -n -e "${BOLD}${PURPLE}Please enter your QA DNS Server address? ${CYAN}[e.g. 8.8.8.8]${NONE} \n"
 read ip
 sed -i "s/qaip/$ip/g" /etc/vpndnsutils.conf
 
-echo -n "Please enter your PRD DNS Server address? [e.g. 8.8.8.8] "
+echo -n -e "${BOLD}${PURPLE}Please enter your PRD DNS Server address? ${CYAN}[e.g. 8.8.8.8]${NONE} \n"
 read ip
 sed -i "s/prdip/$ip/g" /etc/vpndnsutils.conf
 
-
 systemctl start vpndnsutils
+if [ $? -eq 0 ]; then
+    echo -e "${GREEN}Service started successfuly.${NONE}"
+    sleep 5
+else
+    echo -e "${RED}Error.${NONE}"
+    sleep 5
